# Generated by Django 4.0.4 on 2022-04-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lead', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('number_of_members', models.IntegerField()),
            ],
        ),
    ]
