# Generated by Django 4.0.4 on 2022-04-26 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_member_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='ministry',
        ),
    ]
