# Generated by Django 4.0.4 on 2022-04-26 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_member_ministry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='verse',
        ),
    ]
