# Generated by Django 4.0.4 on 2022-04-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_member_verse'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='members',
            field=models.ManyToManyField(to='main_app.member'),
        ),
    ]
